feat: creating extension configuration registry
containers/podman-desktop-extension-ai-lab pull request #1278
Opened 2024-06-24 10:41 UTC by axel7083

### What does this PR do?

Creating a dedicated registry to hold configuration (preferences) logic.

### Notable changes

- ConfigurationRegistry manage the `ai-lab.models.path``previously managed by `ModelsManager`
- Creating frontend store holding the configuration values

### Screenshot / video of UI

### What issues does this PR fix or reference?

### How to test this PR?

- [x] Unit tests has been provided

2024-06-25 06:07 UTC, jeffmaury requested changes
Should be splut in 2 PRs as it mixes 2 different concerns

2024-06-25 09:26 UTC, axel7083 commented
> Should be splut in 2 PRs as it mixes 2 different concerns

@jeffmaury I updated the PR to only focus on the creation of the ConfigurationRegistry

2024-06-28 06:21 UTC, jeffmaury commented on packages/backend/src/registries/ConfigurationRegistry.ts
> +const CONFIGURATION_SECTIONS: string[] = ['ai-lab.experimentalGPU', 'ai-lab.models.path'];
```suggestion
const CONFIGURATION_SECTIONS: string[] = ['ai-lab.models.path'];
```

2024-06-28 09:32 UTC, jeffmaury approved these changes
LGTM

2024-06-28 10:10 UTC, merged