chore(models): remove the hw property
containers/podman-desktop-extension-ai-lab pull request #1433
Opened 2024-07-24 12:57 UTC by axel7083

### What does this PR do?

The `hw` property was useless and should not be on the model interface as it does not depend on the model. Removing it, it could be re-introduced on the InferenceServer, but currently it is missleading with the GPU acceleration.

### Screenshot / video of UI

### What issues does this PR fix or reference?

### How to test this PR?

- [x] existing tests ensure no regression

2024-07-24 12:59 UTC, axel7083 commented
See https://github.com/containers/podman-desktop-extension-ai-lab/issues/1434 for follow-up

2024-07-25 06:41 UTC, jeffmaury requested changes
Putting on hold as it was part of the initial mockup and needs discussion

2024-07-25 14:45 UTC, benoitf approved these changes

2024-07-26 06:17 UTC, jeffmaury approved these changes
LGTM

2024-07-26 08:56 UTC, merged