chore(test): testing increased deploy timeout
containers/podman-desktop-extension-ai-lab pull request #1595
Opened 2024-08-26 13:26 UTC by ScrewTSW

### What does this PR do?
* Increase timeout for AI app deploy
* Parametrize deploy methods

### Screenshot / video of UI
https://github.com/containers/podman-desktop-extension-ai-lab/actions/runs/10741074035/job/29790629355

### What issues does this PR fix or reference?
#1504 

### How to test this PR?

2024-08-26 14:09 UTC, benoitf approved these changes

2024-08-26 15:13 UTC, odockal requested changes

2024-08-26 15:13 UTC, odockal commented on tests/playwright/src/ai-lab-extension.spec.ts
> +  describe(`Verify Podman Machine details`, async () => {
Add this check after extension installation.

2024-08-26 15:13 UTC, odockal commented on tests/playwright/src/ai-lab-extension.spec.ts
> +      await pdRunner.screenshot('ai-lab-tests-resources-page.png');
you have fixed the missing format. +1.

2024-08-26 15:13 UTC, odockal commented on tests/playwright/src/ai-lab-extension.spec.ts
> +  describe(`Verify Podman Machine details`, async () => {
Or add a check for podman machine is present the same way as here: https://github.com/containers/podman-desktop-extension-bootc/blob/main/tests/playwright/src/bootc-extension.spec.ts#L68

2024-08-26 17:39 UTC, jeffmaury reviewed
Looks to me that this PR has changes that are not related to timeout update

2024-08-27 08:37 UTC, ScrewTSW commented
> Looks to me that this PR has changes that are not related to timeout update

the screenshot and machine presence verification is there for debugging purposes, we are still trying to figure out why the model fails to upload to the machine on CI

2025-01-29 15:33 UTC, closed without merging