feat: add GPU banner to Podman AI Lab pages
containers/podman-desktop-extension-ai-lab pull request #1850
Opened 2024-10-07 13:47 UTC by jeffmaury

Fixes #1591

### What does this PR do?

Add a new banner to all Podman AI Lab pages 

### Screenshot / video of UI

### What issues does this PR fix or reference?

#1591

### How to test this PR?

1. Make sure the GPU experimental flag is off
2. Navigate to one of the Podman AI Lab pages and check the banner is displayed
3. Verify banner disappear if one of the button is clicked

2024-10-07 14:09 UTC, axel7083 reviewed
![image](https://github.com/user-attachments/assets/3169edf6-e779-4605-b5ff-82dd258b9948)

I must say this is very intrusive, and do not really fit well in the style .

The checkbox do not really make sense IMO, as when you click on it, the banner just disappear, checkbox means you can enabled/disabled something, here this is an action, and should be a button.

2024-10-09 12:51 UTC, benoitf reviewed
you might add a smaller PR having all the flags being introduced, new methods etc but not the UI

so at least we could merge early this part

2024-10-10 11:09 UTC, benoitf commented on packages/frontend/src/lib/notification/GPUPromotion.spec.ts
> +
I don't get why there the usage of vi.hoisted

AFAIK we don't need it

I commented about that on this issue: https://github.com/containers/podman-desktop-extension-ai-lab/pull/1849

2024-10-10 11:11 UTC, benoitf commented on packages/frontend/src/lib/notification/GPUPromotion.spec.ts
> +}));
you can mock more easily the store 
https://github.com/containers/podman-desktop-extension-ai-lab/pull/1849#discussion_r1795172109

2024-10-10 11:11 UTC, benoitf commented on packages/frontend/src/lib/notification/GPUPromotion.svelte
> +}
I don't see that being covered in the unit tests

2024-10-10 13:38 UTC, benoitf approved these changes
about the UI itself, it may evolve by follow-ups on my end

2024-10-11 06:40 UTC, Firewall requested changes

2024-10-11 06:40 UTC, Firewall commented on packages/frontend/src/lib/notification/GPUPromotion.svelte
> +  'GPU support is not enabled. Podman AI Lab supports GPU on Windows on MacOS.\n\nThis greatly enhance the developer experience when running inference servers. We recommend you to enable it.';
```suggestion
  'GPU support is not enabled. Podman AI Lab supports GPU on Windows on MacOS.\n\nThis greatly enhances the developer experience when running inference servers. We recommend you to enable it.';
```

2024-10-11 06:56 UTC, Firewall approved these changes

2024-10-11 08:50 UTC, axel7083 approved these changes

2024-10-11 15:44 UTC, merged