chore: update release procedure
containers/podman-desktop-extension-ai-lab pull request #1945
Opened 2024-10-17 15:21 UTC by deboer-tim

### What does this PR do?

I think I was the first person to try the release procedure, and there were a few things that were out of date or clearly copied from Podman Desktop.

- There is no label kind/release (and I don't think it's worth creating one).
- Simplified to 'maintainers', since it's not necessarily the same set of people.
- The release timeline was just copied from Podman Desktop and completely wrong this time - at least clarified that's when we're releasing at the same time.
- Improved ordering of / simplified closing the release vs issues in it.
- Version bump PR is not auto-merged, changed the wording.
- Clarified it's the catalog that actually makes the release visible.
- Moved checking the published image to the correct place in the workflow (before we test it).
- Simplified/reorganized/reformatted the testing and publishing sections.
- Minor wording improvements.

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Related to #1842.

### How to test this PR?

N/A

2024-10-17 15:38 UTC, axel7083 approved these changes
Thanks for updating the document !

2024-10-18 06:32 UTC, jeffmaury requested changes

2024-10-18 06:32 UTC, jeffmaury commented on RELEASE.md
> +- Create a branch if it does not exist. For example 1.2.1 if 1.2.0 failed. Then, cherry-pick bugfixes into that branch.
We use 1.2.x on Podman Desktop see https://github.com/containers/podman-desktop/blob/56e136426096a6685f6fb5fb509ba2bd2cb2f916/RELEASE.md?plain=1#L54

2024-11-15 15:41 UTC, benoitf commented
setting as draft as there were no updates since one month

2025-03-11 10:19 UTC, jeffmaury commented
@deboer-tim should we switch it to normal PR ?

2025-04-04 16:15 UTC, deboer-tim commented
Missed the notification, I'll close for now.

2025-04-04 16:15 UTC, closed without merging