Lint staged
containers/podman-desktop-extension-ai-lab pull request #1986
Opened 2024-10-24 16:19 UTC by maryamtahhan

### What does this PR do?
Enable lint staged in husky 

### How to test this PR?

Make a change in a markdown file, commit the change to git and see that the appropriate checks are invoked

```
❯ git commit --signoff -m "chore: test"
✔ Preparing lint-staged...
❯ Running tasks for staged files...
  ❯ package.json — 1 file
    ❯ *.{js,ts,tsx} — 1 file
      ⠙ eslint . --cache --fix
      ◼ prettier --write -u
    ↓ *.{json,md} — no files
◼ Applying modifications from tasks...
◼ Cleaning up temporary files...
```

2024-10-24 16:57 UTC, jeffmaury requested changes

2024-10-24 16:57 UTC, jeffmaury commented on .husky/commit-msg
> +pnpm dlx commitlint --edit $1
Please copy this file from https://github.com/containers/podman-desktop-extension-bootc/blob/main/.husky/commit-msg

2024-10-24 16:57 UTC, jeffmaury commented on .husky/pre-commit
> +pnpm dlx lint-staged
Please copy this file from https://github.com/containers/podman-desktop-extension-bootc/blob/main/.husky/pre-commit

2024-10-24 16:57 UTC, jeffmaury commented on package.json
> +    "prepare": "husky && husky install"
husky install is not required anymore

2024-10-24 16:57 UTC, jeffmaury commented on package.json
> +    "husky": "^8.0.0"
Use latest version of husky

2024-10-25 11:35 UTC, closed without merging

2024-10-25 11:35 UTC, maryamtahhan commented
Putting all changes into https://github.com/containers/podman-desktop-extension-ai-lab/pull/1984