fix: update catalog with latest ai-lab-recipes
containers/podman-desktop-extension-ai-lab pull request #2121
Opened 2024-11-19 16:29 UTC by jeffmaury

Fixes #2120

### What does this PR do?

Update the catalog with latest released version of recipes

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#2120 

### How to test this PR?

Run recipes

2024-11-19 17:03 UTC, benoitf approved these changes
LGTM but I have not tested all the recipes

2024-11-19 17:29 UTC, feloy commented
I get an error with the summarizer:

![summarizer-bug](https://github.com/user-attachments/assets/7fe46c14-c9f4-485b-8565-b607e2a4ba3f)

2024-11-19 18:18 UTC, jeffmaury commented
> I get an error with the summarizer (with an .MD file, it worked with a .TXT file):
> 
> ![summarizer-bug](https://private-user-images.githubusercontent.com/9973512/387769971-7fe46c14-c9f4-485b-8565-b607e2a4ba3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNDA1NTMsIm5iZiI6MTczMjA0MDI1MywicGF0aCI6Ii85OTczNTEyLzM4Nzc2OTk3MS03ZmU0NmMxNC1jOWY0LTQ4NWItODU2NS1iNjA3ZTJhNGJhM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTlUMTgxNzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE3NGU1NmYzMTk1NzEyYTUwNzQ5ZDA1YzhmODkxMzZkNTc0NDlhNTdkMmYxNGEwMDUyYzg3NDYxMWUyOTZkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.acIGqXQn1KuJYCInwMWPmDoLLIN8H9fmdSXn4kB-GMg)

I don't think this is related to this PR I think the application only supports .TXT and .PDF files

2024-11-20 08:29 UTC, feloy commented
> > I get an error with the summarizer (with an .MD file, it worked with a .TXT file):
> > ![summarizer-bug](https://private-user-images.githubusercontent.com/9973512/387769971-7fe46c14-c9f4-485b-8565-b607e2a4ba3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNDA1NTMsIm5iZiI6MTczMjA0MDI1MywicGF0aCI6Ii85OTczNTEyLzM4Nzc2OTk3MS03ZmU0NmMxNC1jOWY0LTQ4NWItODU2NS1iNjA3ZTJhNGJhM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTlUMTgxNzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE3NGU1NmYzMTk1NzEyYTUwNzQ5ZDA1YzhmODkxMzZkNTc0NDlhNTdkMmYxNGEwMDUyYzg3NDYxMWUyOTZkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.acIGqXQn1KuJYCInwMWPmDoLLIN8H9fmdSXn4kB-GMg)
> 
> I don't think this is related to this PR I think the application only supports .TXT and .PDF files

The problem I can see is that the interface is displaying that the supported formats are TXT, PDF and MD.

I proposed a patch on the ai-lab-recipes repo to support MD files: https://github.com/containers/ai-lab-recipes/pull/815

2024-11-20 09:22 UTC, gastoner approved these changes
Codewise LGTM

2024-11-20 16:01 UTC, feloy commented
> 
> PR updated can you retry ?

This works now, thanks

2024-11-21 09:13 UTC, jeffmaury commented
> For the RAG, I get this error:
> 
> ![rag_error](https://private-user-images.githubusercontent.com/9973512/388173948-651182ce-ab30-4a6d-bc6b-7e0391654c8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODA2MTIsIm5iZiI6MTczMjE4MDMxMiwicGF0aCI6Ii85OTczNTEyLzM4ODE3Mzk0OC02NTExODJjZS1hYjMwLTRhNmQtYmM2Yi03ZTAzOTE2NTRjOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMDkxMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M3NmU3ZDJiZmU2NDM4ZGQyMzkzZjgxMDU0YjAwOGY4OWM1OTJmYTc5OGExNzQ1YzAyODFjYjFiODc2N2VmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bra0iOki56kkcvgiMouU0VPmt0mx0E72_1zKJhGoSF4)

Let me check because it was supposed to be fixed

2024-11-21 10:09 UTC, jeffmaury commented
> > For the RAG, I get this error:
> > ![rag_error](https://private-user-images.githubusercontent.com/9973512/388173948-651182ce-ab30-4a6d-bc6b-7e0391654c8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODA2MTIsIm5iZiI6MTczMjE4MDMxMiwicGF0aCI6Ii85OTczNTEyLzM4ODE3Mzk0OC02NTExODJjZS1hYjMwLTRhNmQtYmM2Yi03ZTAzOTE2NTRjOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMDkxMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M3NmU3ZDJiZmU2NDM4ZGQyMzkzZjgxMDU0YjAwOGY4OWM1OTJmYTc5OGExNzQ1YzAyODFjYjFiODc2N2VmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bra0iOki56kkcvgiMouU0VPmt0mx0E72_1zKJhGoSF4)
> 
> Let me check because it was supposed to be fixed

Works on my machine :)

2024-11-21 10:55 UTC, feloy commented
> > > For the RAG, I get this error:
> > > ![rag_error](https://private-user-images.githubusercontent.com/9973512/388173948-651182ce-ab30-4a6d-bc6b-7e0391654c8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODA2MTIsIm5iZiI6MTczMjE4MDMxMiwicGF0aCI6Ii85OTczNTEyLzM4ODE3Mzk0OC02NTExODJjZS1hYjMwLTRhNmQtYmM2Yi03ZTAzOTE2NTRjOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMDkxMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M3NmU3ZDJiZmU2NDM4ZGQyMzkzZjgxMDU0YjAwOGY4OWM1OTJmYTc5OGExNzQ1YzAyODFjYjFiODc2N2VmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bra0iOki56kkcvgiMouU0VPmt0mx0E72_1zKJhGoSF4)
> > 
> > 
> > Let me check because it was supposed to be fixed
> 
> Works on my machine :)

Works on my machine now :) I don't know what is different from the previous test

2024-11-21 10:57 UTC, feloy requested changes

2024-11-21 10:57 UTC, feloy commented on packages/backend/src/assets/ai.json
>        "basedir": "recipes/natural_language_processing/chatbot-java",
```suggestion
      "basedir": "recipes/natural_language_processing/chatbot-java-quarkus",
```

2024-11-21 14:04 UTC, feloy approved these changes
tested all recipes, all are working for me

https://github.com/containers/ai-lab-recipes/pull/815 has been merged. Is it worth waiting for a new release to include it?

2024-11-21 14:18 UTC, jeffmaury commented
> tested all recipes, all are working for me
> 
> [containers/ai-lab-recipes#815](https://github.com/containers/ai-lab-recipes/pull/815) has been merged. Is it worth waiting for a new release to include it?

I'm still fighting for the release as I can't make the Quarkus recipe to work so I would delay as the goal of this release is to fix the errors on existing recipes

2024-11-22 12:53 UTC, feloy commented
Is the tag `1.3.3.1` already done on the `ai-lab-recipes`? I cannot see it

2024-11-22 15:00 UTC, jeffmaury commented
> Is the tag `1.3.3.1` already done on the `ai-lab-recipes`? I cannot see it

https://github.com/containers/ai-lab-recipes/releases/tag/v1.3.0.1

2024-11-25 06:52 UTC, feloy commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
```suggestion
      "ref": "v1.3.0.1",
```

2024-11-25 06:52 UTC, feloy commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
```suggestion
      "ref": "v1.3.0.1",
```

2024-11-25 06:52 UTC, feloy commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
```suggestion
      "ref": "v1.3.0.1",
```

2024-11-25 06:52 UTC, feloy commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
```suggestion
      "ref": "v1.3.0.1",
```

2024-11-25 07:45 UTC, jeffmaury commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
Tag renamed for better consistency

2024-11-25 07:45 UTC, jeffmaury commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
Tag renamed for better consistency

2024-11-25 07:45 UTC, jeffmaury commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
Tag renamed for better consistency

2024-11-25 07:45 UTC, jeffmaury commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
Tag renamed for better consistency

2024-11-25 07:45 UTC, jeffmaury commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
Tag renamed for better consistency

2024-11-25 07:46 UTC, jeffmaury commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
Tag renamed for better consistency

2024-11-25 07:46 UTC, jeffmaury commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
Tag renamed for better consistency

2024-11-25 07:46 UTC, jeffmaury commented on packages/backend/src/assets/ai.json
> +      "ref": "v1.3.3.1",
Tag renamed for better consistency

2024-11-25 07:56 UTC, feloy commented
LGTM

2024-11-25 13:16 UTC, merged