fix: capture die events for inference servers
containers/podman-desktop-extension-ai-lab pull request #886
Opened 2024-04-12 09:32 UTC by axel7083

### What does this PR do?

After some investigation, we did not have any logic for external stop events, leading to the server still marked as running for a period of time (until the pull update, which can last up to 10 seconds).

This PR is adding proper management of the `die` container event to improve the reactivity of the updates.

### Screenshot / video of UI

https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/1f80f7fa-62e6-44b2-a253-7f83c5a10cd1

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/893

### How to test this PR?

- [x] unit tests has been provided

2024-04-12 09:35 UTC, benoitf approved these changes

2024-04-12 13:19 UTC, jeffmaury requested changes
Does not fix my use case.

2024-04-15 06:43 UTC, axel7083 commented
> Does not fix my use case.

I will comment on your issue.

2024-04-15 08:44 UTC, lstocchi approved these changes

2024-04-15 13:51 UTC, jeffmaury approved these changes
LGTM

2024-04-15 14:24 UTC, merged